# Generated by Django 3.2 on 2022-06-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('account_name', models.CharField(max_length=40)),
                ('merchant_secret_key', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=20, prefix='', primary_key=True, serialize=False)),
                ('account_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_account_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Sent')], default=0)),
                ('merchant_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_merchant', to='third_party_auth.merchantaccount')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
    ]
