# Generated by Django 3.2 on 2022-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Declined')], default=0),
        ),
    ]
