# Generated by Django 3.2.7 on 2022-05-26 16:02

import apps.payments.utils.receipt_files_path
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(upload_to=apps.payments.utils.receipt_files_path.get_receipt_file_path),
        ),
    ]
