# Generated by Django 3.2 on 2022-06-10 10:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('reference', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(4, 'Third Party Withdraw'), (3, 'Third Party Deposit')])),
                ('status', models.IntegerField(choices=[(0, 'Unverified'), (1, 'Verified'), (2, 'Cancelled')], default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Declined')], default=0)),
                ('merchant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to='users.merchantaccount')),
            ],
            options={
                'unique_together': {('merchant_account', 'reference')},
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionOTP',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('otp_code', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=15, prefix='', primary_key=True, serialize=False)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='third_party_transaction.thirdpartytransaction')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
