# Generated by Django 3.2.7 on 2022-05-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
