# Generated by Django 3.2 on 2022-07-31 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SahibMoneyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(max_length=64)),
                ('account_name', models.CharField(max_length=64)),
                ('account_number', models.CharField(max_length=64)),
                ('iban_number', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('sahibmoneybank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.sahibmoneybank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('banks.sahibmoneybank',),
        ),
    ]
