# Generated by Django 3.2 on 2022-07-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_userbank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sahibmoneybank',
            name='account_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sahibmoneybank',
            name='iban_no',
            field=models.CharField(max_length=50),
        ),
    ]
