# Generated by Django 3.2 on 2022-06-04 15:13

import apps.wallet.utils.receipt_files_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('wallet', '0001_initial'), ('wallet', '0002_auto_20220604_1455'), ('wallet', '0003_rename_bankdetails_bankdetail')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_amount', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=30)),
                ('iban_no', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amount', models.FloatField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_wallet', to='wallet.wallet')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('receipt', models.ImageField(upload_to=apps.wallet.utils.receipt_files_path.get_receipt_file_path)),
                ('status', models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Declined')], default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='P2PTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_receiver_wallet', to='wallet.wallet')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Sent')], default=0)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_bank_details', to='wallet.bankdetails')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
    ]
