# Generated by Django 3.2 on 2022-07-31 11:43

import apps.wallet.utils.receipt_files_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('status', models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Declined')], default=0)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_transactions', to='banks.userbank')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='P2PTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to_wallet', to='wallet.wallet')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.transaction')),
                ('receipt', models.ImageField(upload_to=apps.wallet.utils.receipt_files_path.get_receipt_file_path)),
                ('status', models.IntegerField(choices=[(0, 'Waiting for Approval'), (1, 'Approved'), (2, 'Declined')], default=0)),
                ('bank_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_transations', to='banks.userbank')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('wallet.transaction',),
        ),
    ]
