# Generated by Django 3.2 on 2022-06-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_userbank_user'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='withdrawaltransaction',
            name='bank_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_bank_details', to='banks.userbank'),
        ),
        migrations.DeleteModel(
            name='BankDetail',
        ),
    ]
