# Generated by Django 3.2 on 2022-05-31 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('wallet', '0003_wallettransaction_account_no'), ('wallet', '0004_alter_wallet_total_amount'), ('wallet', '0005_auto_20220530_1754')]

    dependencies = [
        ('wallet', '0002_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='account_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='from_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='to_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_wallet', to='wallet.wallet'),
        ),
    ]
