# Generated by Django 3.2 on 2022-06-04 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20220604_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankDetail',
        ),
    ]
