# Generated by Django 3.2 on 2022-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallettransaction_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
